# Generated by Django 5.0.2 on 2025-03-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_bio_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
