# Generated by Django 5.0.2 on 2025-03-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
